[package]
name = "a1_hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Jinghui Hu<hujinghui@buaa.edu.cn>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
